name: TestDemo
on: push

jobs:
  my-job:
    name: Fisrt Job
    runs-on: windows-2019
    
    steps:
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Download
      shell: powershell
      run: Invoke-WebRequest -Uri "https://archive.org/download/pin-3.30-98830-g1d7b601b3-msvc-windows/pin-3.30-98830-g1d7b601b3-msvc-windows.zip" -OutFile "c:\abc.zip"
      
    - name: Unzip
      shell: cmd
      run: |
        cd c:
        7z x -y c:\abc.zip
        del c:\abc.zip
        mv pin-3.30-98830-g1d7b601b3-msvc-windows pin
          
    - name: MoveTq
      run: git clone https://github.com/opsecko/tiny_tracer.git c:\pin\source\tools\tiny_tracer

    - name: Build
      run: |
        cd c:\pin\source\tools\tiny_tracer
        msbuild /m /p:Configuration=Release /p:PlatformTarget=x64 /p:PlatformToolset=v142 c:\pin\source\tools\tiny_tracer\TinyTracer.vcxproj  
