name: TestDemo
on: push
jobs:
  my-job:
    name: Fisrt Job
    runs-on: windows-2019
    
    steps:
    - name: Download
      shell: powershell
      run: Invoke-WebRequest -Uri "https://software.intel.com/sites/landingpage/pintool/downloads/pin-3.30-98830-g1d7b601b3-msvc-windows.zip" -OutFile "c:\abc.zip"
      
